language: node_js

node_js:
  - 0.10
  - 0.8

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - mysql -e 'create database relatable;'
  - mysql relatable < t/ddl/mysql.sql
  - psql -c 'create database relatable;' -U postgres
  - psql -U postgres relatable < t/ddl/postgresql.sql
  - mv t/configuration.travis.json configuration.json
  - npm install
  - npm install istanbul coveralls
